### ISSUE TITLE
Sponsors footer not working

### ISSUE THREAD

**Issue by cbail** [compsocialscience/summer-institute#1243]
My html is not good enough to figure out how to render final_logos.png at the right size. There is another file called final_logos.svg, but it depends upon three logos that are also in the folder.

**Comment by ngambino0192** [comment]
this has been addressed in: https://github.com/compsocialscience/summer-institute/commit/b0aafc56134894325656cc96aed562d1948b160e

please review and comment when you can. you can modify this `max-width` property as needed to gauge the size of the logo.

**Comment by cbail** [comment]
This worked like a charm- thanks Nick.
