### ISSUE TITLE
"Learn More" buttons on Location Pages redirect to wrong pages

### ISSUE THREAD

**Issue by cbail** [compsocialscience/summer-institute#1246]
"Learn More" buttons beneath each location should redirect to the main "overview" page for each site; not the apply page (the Apply button already links to the apply page). Nick G./Luke can you please take a look? I tried to tweak but again my html sucks :(

**Comment by ngambino0192** [comment]
@cbail good catch!

this required a tweak to the bootstrap style: https://github.com/compsocialscience/summer-institute/commit/4a63b832c7689ac5ef6ef5e3dc96d791325d3be7

**Comment by cbail** [comment]
It worked thanks!
