### ISSUE TITLE
Text Size "Curriculum/Learn Online Page"

### ISSUE THREAD

**Issue by cbail** [compsocialscience/summer-institute#1247]
The text size in the "Overview" section of the Curriculum page (now called the Learn Online) page, is larger than the other pages.

**Comment by ngambino0192** [comment]
@cbail this has been addressed, the titles are now being controlled by the appropriate html styling in https://github.com/compsocialscience/summer-institute/commit/9cb343ab77a45a1be5ba74ea23617591e3e99f9b

**Comment by cbail** [comment]
Hi Nick- I think this may have fixed the title of the page but not the main text of the "overview". The part that still looks too big to me begins with: "We provide state-of-the art training in a range of different areas in computational social science from ethics to text analysis and mass collaboration...." Am I correct that your patch addressed the size of the "Overview" heading there instead of the text above? Or did I somehow mess up the merge? If so sorry!

**Comment by ngambino0192** [comment]
@cbail thanks for pointing this out. You are correct, and I have modified the html to pull in markdown from the root `curriculum.md`. This makes it uniform with the rest of the site's body content.

Can you please review my branch: `learning-materials-markdown` and let me know if it looks better to you?

Feel free to merge the branch into `master`
