### ISSUE TITLE
Add contact email

### ISSUE THREAD

**Issue by cbail** [compsocialscience/summer-institute#1308]
Hi Nick/Luke:

One more small request: can we please add the following contact email to the footer: rsfcompsocsci@gmail.com? I tried to do it myself but couldn't figure out how to do it without adding an entire "contact" page, which seems overkill.

Many thanks,
Chris

**Comment by ngambino0192** [comment]
@cbail this has now been addressed. As this was a small change, I went ahead and deployed this to the production site: https://compsocialscience.github.io/summer-institute/

Please let me know if that looks good to you!

Thanks

**Comment by msalganik** [comment]
Looks good.  I'm closing now.
