### ISSUE TITLE
Changing URL

### ISSUE THREAD

**Issue by cbail** [compsocialscience/summer-institute#1509]
Is it possible to change our URL to www.sicss.org? If so, about how much work would this be (and how much cost)? Would there be any additional hassles (e.g. yearly domain registration). Thanks.

**Comment by msalganik** [comment]
@cbail I love this idea, but that's already taken unfortunately: https://sicss.org/

I already have a bunch of domain registrations so it is not hard for me to add another. 

If you have other ideas let me know.  

I don't think it is hard for @lukebaker to make this change, once we own the domain name.

**Comment by cbail** [comment]
Huh weird- when I searched the other day I got a DNS error. Oh well. Maybe sicss.net? Looks like it is available.

**Comment by cbail** [comment]
Or maybe sicss.io?

**Comment by msalganik** [comment]
Hmmm.  I don't like sicss.net and sicss.io is $50 per year.  I'd suggest that we table this until some new inspiration strikes.

**Comment by cbail** [comment]
Ok- I definitely don't think its an urgent issue.

**Comment by msalganik** [comment]
This is done.  I'm closing this issue.
