### ISSUE TITLE
Would it be possible to modify the people.yml ?

### ISSUE THREAD

**Issue by jmigozzi** [compsocialscience/summer-institute#1701]
Hi there, this is surely a trivial question, but how could we modify the "people" section on the website ? We don't have any Teaching Assistants for the Paris site, so it would look better if we could remove the "teaching assistants" section from the website ? 

Sorry for such a request, and many thanks in advance !

**Comment by msalganik** [comment]
Julian is part of SICSS-Paris, which has been postponed until 2021.  Therefore, I'm going to close this now.
