### ISSUE TITLE
Add more visual weight to slides and code links in schedule

### ISSUE THREAD

**Issue by lukebaker** [compsocialscience/summer-institute#327]
In the Slack channel, Matt requested more visual weight of the slides and code links in the schedule.

**Comment by lukebaker** [comment]
@msalganik the "name" field for the schedule items can include any markdown. In other words, if there's something we can do with markdown that adds enough visual weight, then we don't need to update the schedule template (updating the schedule template is also possible if we need to do that). Here are a few things that I tinkered with:

* Bolding the text:
  ![127 0 0 1_4000_summer-institute_2018_ 2](https://user-images.githubusercontent.com/84748/42092710-d5520abe-7b77-11e8-8bfa-ac01733588ef.png)
* On new line and bolded:
  ![127 0 0 1_4000_summer-institute_2018_](https://user-images.githubusercontent.com/84748/42092812-46bb7c08-7b78-11e8-9cb0-46827d700d70.png)
* On new line as h3:
  ![127 0 0 1_4000_summer-institute_2018_ 3](https://user-images.githubusercontent.com/84748/42092725-eb768810-7b77-11e8-826f-a704993e9e9c.png)
* On new line as h3 with label:
  ![127 0 0 1_4000_summer-institute_2018_ 4](https://user-images.githubusercontent.com/84748/42092740-fc8b504a-7b77-11e8-919c-72681666682e.png)
* Using a blockquote:
  ![127 0 0 1_4000_summer-institute_2018_ 5](https://user-images.githubusercontent.com/84748/42092756-0f25b3e4-7b78-11e8-8472-671b410df9bc.png)

Do any of those or some variation on those add the sort of visual weight you were looking for? If we're not finding any markdown-only options that look good, we can explore template modifications.

**Comment by lukebaker** [comment]
Here's another option using a bullet point:
![127 0 0 1_4000_summer-institute_2018_ 1](https://user-images.githubusercontent.com/84748/42096358-19b0b114-7b83-11e8-823a-09059705d2d2.png)

**Comment by msalganik** [comment]
Thanks @lukebaker. I was trying to play with that, but I couldn't get it to work.  Could you send the markdown?

**Comment by lukebaker** [comment]
Here's a sample for using a bullet point in `_data/2018/schedule.yml`:

```yaml
    - name: |
        9:30 - 10:00 Introduction to computational social science
    
        * [slides](https://github.com/compsocialscience/summer-institute/blob/master/2018/materials/day1-intro-ethics/02-intro-computational-social-science.pdf)
```

**Comment by msalganik** [comment]
This all works great.  We've gone with the final option, the one with bullets.  It is all set now.  Thanks.
