### ISSUE TITLE
Split "Schedule & Materials" into two tabs "Schedule" and "Teaching & learning materials"

### ISSUE THREAD

**Issue by lukebaker** [compsocialscience/summer-institute#328]
@msalganik said:

> Can we split the “Schedule & Materials” tab into two tabs “Schedule” and “Teaching & learning materials”.  If folks click on schedule they should be taken to the schedule (just like now, no changes).  If folks click on “Teaching & learning materials” they should be taken to a new page similar to the apply page (), which has its own .md file.  We will then copy the information in the schedule.md file and  restyle it.  This is something that we will only do at the end of the institute so we are not worried about the two things getting out of sync.

**Comment by lukebaker** [comment]
@msalganik You mentioned wanting to restyle the "Teaching & learning materials" page. Do you anticipate that page being pure Markdown or will it need some custom HTML and CSS styles? The current schedule has custom HTML and uses data from the YAML file. Pure Markdown has the benefit of being easily updated / modified by whoever is charged with creating / updating that page.

In https://github.com/compsocialscience/summer-institute/commit/69d5e95, I've created a [basic stub of that page](https://compsocialscience.github.io/summer-institute/2018/teaching-learning-materials) in by copying the data from the schedule.yml file and doing some small changes (remove all but the `name:` lines, removing `name: time - time`, etc.). I also added a [link to that page in the navigation](https://github.com/compsocialscience/summer-institute/blob/69d5e9562a2406da7d15bf1e3ab783a35bb99f9e/_data/2018/navigation.yml#L7-L8), but have it commented out for now. Removing the `#` should make that link live on the site.

Is this a good starting point for y'all to take it from here or did you have something else in mind?

**Comment by msalganik** [comment]
This looks great.  Basic Markdown is good.  I've adjusted the nav.  We can take it from here.  Thanks.
