### ISSUE TITLE
add Princeton orange as a possible color for background of hero

### ISSUE THREAD

**Issue by msalganik** [compsocialscience/summer-institute#329]

**Comment by lukebaker** [comment]
This is all set! There was a orange option, but the 2019 hero.yml was misspelled, so it wasn't showing any color. However, I specifically added a princeton-orange option using the orange on white recommendation from the [office of communications](https://communications.princeton.edu/guides-tools/logo-brand-assets).

**Comment by msalganik** [comment]
👍
