### ISSUE TITLE
hosting large html files on github

### ISSUE THREAD

**Issue by msalganik** [compsocialscience/summer-institute#337]
We are in the process of archiving all of our teaching materials and we've run into a bit of a hiccup.

Some of the slides are created in html.  Right now we are linking to them on another platform, but we'd like to link to them on github so that all the materials are in one place.  

For example, "What is digital trace data?" Slides.  This currently links to https://cbail.github.io/SICSS_What_is_Digital_Trace.html

However, we would like to link to: https://github.com/compsocialscience/summer-institute/blob/master/2018/materials/day2-digital-trace-data/what-is-digital-trace-data/SICSS_What_is_Digital_Trace.html

However, I can't seem to successfully link to this html file on github.

I've tried using http://htmlpreview.github.io/ but it does not seem to be working.

Ideas?

**Comment by lukebaker** [comment]
How about this link: https://compsocialscience.github.io/summer-institute/2018/materials/day2-digital-trace-data/what-is-digital-trace-data/SICSS_What_is_Digital_Trace.html

Is that what you were hoping for?

**Comment by msalganik** [comment]
That's it exactly!  Thanks.
