### ISSUE TITLE
Allow partner locations to specify style of apply button

### ISSUE THREAD

**Issue by lukebaker** [compsocialscience/summer-institute#540]
We have in the past highlighted the "Apply" button by making it blue when still accepting applications and reverting to the default gray when not accepting applications. However, this has been changed via CSS. It'd be nice to allow this "highlighting" to be specified in the YAML for that navigation.

**Comment by cbail** [comment]
Sounds good- this is not super urgent on our end but would be nice to have. Thanks.

**Comment by msalganik** [comment]
Can we also make it possible to completely remove the apply button from this page (https://compsocialscience.github.io/summer-institute/locations#2020)?  We now have it there for many sites that are postponed.  I can see why we might want to keep the application information available at each partner location, but we don't need to drive people to apply to the postponed sites.
